# @package task


model_configs:
  - _target_: model.config.ModelConfig
    name: "QizhiPei/biot5-plus-base-chebi20"
    representation_type: selfies
    load_model:
      _target_: model.config.LoadModel
      from_pretrained: true
    tokenizer_config:
      _target_: model.config.TokenizerConfig
