# @package task
eval_config:
  data_config:
    data_path: ${oc.env:DATA_PATH}/molt5_splits/test_pcdes.csv

  predict_config:
    # cache_paths:
    # smiles: ""

    confidence_config:
      confidence: neg_perplexity

  device: gpu
  ensemble: false

model_configs:
  - _target_: model.config.ModelConfig
    name: "google/t5-v1_1-base"
    checkpoint_path: "${oc.env:EXTERNAL_PATH}/checkpoints/hyeontae/ft_text2mol_smiles_micro_base_pcdes_2025-01-25_17-10-08_stereo/checkpoint-50000/pytorch_model.bin"
    representation_type: smiles
    load_model:
      _target_: model.config.LoadModel
      from_pretrained: false
    tokenizer_config:
      _target_: model.config.TokenizerConfig
      additional_tokens_paths:
        - "asset/mol_vocabs/frag.txt"
        - "asset/mol_vocabs/selfies.txt"

