# @package task

train_config:
  device: "gpu"
  seed: 42
  shot: 1
  do_compile: False
  batch_size: 48
  grad_acc: 12
  optim_config:
    name: adamw
    weight_decay: 0.0
    base_lr: 2e-3
    total_steps: 50000
    grad_clip: 30.0
    lr_scheduler_config:
      name: cosine
      warmup_steps: 1000

  importance_weight_config:
    _target_: train.config.ImportanceWeightConfig
    temperature: 5
    log_importance_weighted_loss: true

  eval_config:
    task: "text2mol"
    every_steps: 5000
    wandb:
      _target_: train.config.Wandb
      project: "CAMT5"
      run_name: "ct_pt_text2mol_frag_micro_base_T_5_camt5_v3_${now:%Y-%m-%d_%H-%M-%S}_stereo"

  checkpoint:
    every_steps: 10000
    path: ${oc.env:EXTERNAL_PATH}/checkpoints/hyeontae/ct_pt_text2mol_frag_micro_base_T_5_camt5_v3_${now:%m%d}_stereo

  logging_config:
    every_steps: 100
    accuracy: true
    grad_l2: true
    weights_l2: true

model_config:
  name: "google/t5-v1_1-base"
  checkpoint_path: "${oc.env:EXTERNAL_PATH}/checkpoints/hyeontae/pt_frag_micro_base_camt5_v3_T_1_4_batched_2025-01-12_22-48-06_stereo/checkpoint-100000/pytorch_model.bin"
  representation_type: frag
  load_model:
    from_pretrained: false
  tokenizer_config:
    additional_tokens_paths:
      - "asset/mol_vocabs/frag_camt5_v3.txt"
      - "asset/mol_vocabs/selfies.txt"

data_config:
  num_workers: 8

  continual_pretrain_data_config:
    t2m_data_ratio: 0.75
    input_length: 512

    t2m_data_path: ${oc.env:DATA_PATH}/tasks/pub_chem_data_v3.csv

    mlm_probability: 0.15
    mean_noise_span_length: 3.0

  token_importance_config:
    _target_: train.config.TokenImportanceConfig
    token_importance: atom_count
    special_token_importance: 0
