# @package task

train_config:
  device: "gpu"
  seed: 42
  shot: 1
  do_compile: False
  batch_size: 48
  grad_acc: 6
  optim_config:
    name: adamw
    weight_decay: 0.0
    base_lr: 2e-3
    total_steps: 50000
    grad_clip: 30.0
    lr_scheduler_config:
      name: cosine
      warmup_steps: 1000

  eval_config:
    task: "text2mol"
    every_steps: 5000
    wandb:
      _target_: train.config.Wandb
      project: "CAMT5"
      run_name: "ft_text2mol_frag_micro_base_camt5_v3_brics_w_pubchem_${now:%Y-%m-%d_%H-%M-%S}_stereo"

  checkpoint:
    every_steps: 10000
    path: ${oc.env:EXTERNAL_PATH}/checkpoints/hyeontae/ft_text2mol_frag_micro_base_camt5_v3_brics_w_pubchem_${now:%Y-%m-%d_%H-%M-%S}_stereo

  logging_config:
    every_steps: 100
    accuracy: true
    grad_l2: true
    weights_l2: true

model_config:
  name: "google/t5-v1_1-base"
  checkpoint_path: "${oc.env:EXTERNAL_PATH}/checkpoints/hyeontae/"
  representation_type: frag
  load_model:
    from_pretrained: false
  tokenizer_config:
    additional_tokens_paths:
      - "asset/mol_vocabs/frag_brics.txt"
      - "asset/mol_vocabs/selfies.txt"

data_config:
  num_workers: 8

  text_2_mol_data_config:
    max_seq_len: 512
    max_target_len: 512
    exec_file_path: ${oc.env:DATA_PATH}/ni_dataset.py
    data_dir: ${oc.env:DATA_PATH}/splits/mol_text/text2mol_frag_micro_camt5_v3_brics_w_pubchem_stereo
    task_dir: ${oc.env:DATA_PATH}/tasks
    max_num_instances_per_task: 100000
